### ISSUE TITLE
Bump version of `DynamicQuantities` ? 

### ISSUE THREAD

**Issue by BambOoxX** [JuliaML/DataScienceTraits.jl#12]
Hi guys, I'm currently working on projects involving `ModelingToolkit` and `Meshes`/`GeoTables`, but I'm locked in terms of versions because of `DynamicQuantities`. Is there a way to bump or relax the version constraint on this dependency ?

**Comment by juliohm** [comment]
@BambOoxX feel free to submit a PR. Can you please confirm that the latest versions pass all tests?

**Comment by BambOoxX** [comment]
I just tested with `DynamicQuantities` v0.13.0 and the tests seem to be ok. I'm a bit rusty with PR's though.
